-- zh-CN.lua (chinese - simplified)
return {
    misc = {
        dictionary = {
            b_spectral_cards="符卡",
            b_planet_cards="角色牌",
            b_stat_planets="角色牌",
            b_stat_spectrals="符卡",
            b_stat_tarots="地点牌",
            b_tarot_cards="地点牌",
            k_arcana_pack="地点包",
            k_celestial_pack="角色包",
            k_dwarf_planet="角色牌",
            k_face_cards="贤者牌",
            k_planet="角色牌",
            k_planet_q="角色牌？",
            k_plus_planet="+1 角色牌",
            k_plus_spectral="+1 符卡",
            k_plus_tarot="+1 地点牌",
            k_spectral="符卡",
            k_tarot="地点牌",
            k_spectral_pack="符卡包",
        },
        labels={
            planet="角色牌",
            pluto_planet="角色牌",
            tarot="地点牌",
        	    },
    },
    descriptions = {
        alt_texture = {
            alt_tex_th_jokers = {
			name = "小丑牌",
            j_8_ball={
                name="地下偶像",
                text={
                    "打出的每一张{C:attention}8{}",
                    "有{C:green}#1#/#2#{}几率在计分时",
                    "生成一张{C:tarot}地点牌{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            j_abstract={
                name="阴阳玉",
                },
            j_acrobat={
                name="门扉",
                },
            j_ancient={
                name="鸟居",
                },
            j_arrowhead={
                name="樱花",
                },
            j_astronomer={
                name="求闻史记",
                text={
                    "所有{C:planet}角色牌{}",
                    "和{C:planet}角色补充包{}",
                    "在商店内都{C:attention}免费",
                },
                unlock={
                    "发现所有",
                    "{E:1,C:planet}角色牌{}",
                },
            },
            j_banner={
                name="驱魔棒",
                },
            j_baron={
                name="八云家",
                },
            j_baseball={
                name="当头棒喝",
                },
            j_blackboard={
                name="黑洞洞",
                },
            j_bloodstone={
                name="玫瑰",
                },
            j_blue_joker={
                name="蓝点",
                },
            j_blueprint={
                name="反狱王",
                },
            j_bootstraps={
                name="赛钱箱",
                },
            j_brainstorm={
                name="外来韦编 ALERT",
                },
            j_bull={
                name="弹幕变大术",
                },
            j_burglar={
                name="小偷！",
                },
            j_burnt={
                name="纵火",
                },
            j_business={
                name="名片",
                text={
                    "打出的{C:attention}贤者牌{}在计分时",
                    "有{C:green}#1#/#2#{}的几率",
                    "获得{C:money}$2{}",
                },
            },
            j_caino={
                name="卡尼奥",
                text={
                    "每当一张{C:attention}贤者牌{}",
                    "被摧毁时",
                    "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
                    "{C:inactive}（当前为{X:mult,C:white} X#2#{C:inactive}倍率）",
                },
            },

            j_campfire={
                name="暴食",
                },
            j_card_sharp={
                name="出千",
                },
            j_cartomancer={
                name="文文。新闻",
                text={
                    "在选择{C:attention}盲注{}时",
                    "生成一张{C:tarot}地点牌{}",
                    "{C:inactive}（必须有空位）",
                },
                unlock={
                    "发现每张",
                    "{E:1,C:tarot}地点牌{}",
                },
            },
            j_castle={
                name="大图书馆",
                },
            j_cavendish={
                name="极限火花",
                },
            j_ceremonial={
                name="杀意",
                },
            j_certificate={
                name="替身地藏",
                },
            j_chaos={
                name="上海人形",
                },
            j_clever={
                name="两对蓝点",
                },
            j_cloud_9={
                name="冰雪聪明",
                },
            j_constellation={
                name="弹幕烟花大会",
                },
            j_crafty={
                name="同花蓝点",
                },
            j_crazy={
                name="顺子P点",
                },
            j_credit_card={
                name="香霖堂20円代金券",
                },
            j_delayed_grat={
                name="怀表",
                },
            j_devious={
                name="顺子蓝点",
                },
            j_diet_cola={
                name="啤酒",
                },
            j_dna={
                name="一只萃香，两只萃香...",
                },
            j_drivers_license={
                name="驾驶执照",
                },
            j_droll={
                name="同花P点",
                },
            j_drunkard={
                name="伊吹瓢",
                },
            j_duo={
                name="剑士",
                },
            j_dusk={
                name="梦境世界",
                },
            j_egg={
                name="毘沙门天的宝塔",
                },
            j_erosion={
                name="欲望吞噬",
                },
            j_even_steven={
                name="尔子田里乃",
                },
            j_faceless={
                name="下克上",
                text={
                    "如果同时弃掉",
                    "{C:attention}#2#{}张或更多张",
                    "{C:attention}贤者牌{}",
                    "获得{C:money}$#1#{}",
                },
            },
            j_family={
                name="破坏狂",
                },
            j_fibonacci={
                name="垒石",
                },
            j_flash={
                name="趁虚而入",
                },
            j_flower_pot={
                name="四季",
                },
            j_fortune_teller={
                name="博丽大结界",
                text={
                    "本赛局内每使用过一张{C:purple}地点牌{}",
                    "这张小丑获得{C:red}+#1#{}倍率",
                    "{C:inactive}（当前为{C:red}+#2#{C:inactive}）",
                },
            },
            j_four_fingers={
                name="骚灵乐团",
                },
            j_gift={
                name="探宝棒",
                },
            j_glass={
                name="完美冻结",
                text={
                    "每摧毁一张",
                    "{C:attention}冰冻牌",
                    "这张小丑获得{X:mult,C:white}X#1#{}倍率",
                    "{C:inactive}（当前为{X:mult,C:white} X#2#{C:inactive}倍率）",
                },
                unlock={
                    "在你的牌组中",
                    "拥有{E:1,C:attention}#1#张",
                    "{E:1,C:attention}#2#{}",
                },
            },
            j_gluttenous_joker={
                name="夏日",
                },
            j_golden={
                name="资金点",
                },
            j_greedy_joker={
                name="秋日",
                },
            j_green_joker={
                name="大妖精",
                },
            j_gros_michel={
                name="八卦炉",
                },
            j_hack={
                name="M-1漫才",
                },
            j_half={
                name="被撕下一半的通缉令",
                },
            j_hallucination={
                name="花果子念报",
                text={
                    "打开任一{C:attention}补充包{}时",
                    "有{C:green}#1#/#2#{}几率",
                    "生成一张{C:attention}地点牌{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            j_hanging_chad={
                name="未断选票",
                },
            j_hiker={
                name="安眠入梦",
                },
            j_hit_the_road={
                name="这里是...纯狐！",
                },
            j_hologram={
                name="月之都明信片",
                },
            j_ice_cream={
                name="刨冰",
                },
            j_idol={
                name="偶像",
                },
            j_invisible={
                name="幽灵聚会",
                },
            j_joker={
                name="P点",
                },
            j_jolly={
                name="对子P点",
                },
            j_juggler={
                name="星熊杯",
                },
            j_loyalty_card={
                name="借书卡",
                },
            j_luchador={
                name="遗照",
                },
            j_lucky_cat={
                name="招财猫",
                },
            j_lusty_joker={
                name="春日",
                },
            j_mad={
                name="两对P点",
                },
            j_madness={
                name="疯狂",
                },
            j_mail={
                name="检查站",
                },
            j_marble={
                name="恋之fumo",
                },
            j_matador={
                name="final stage",
                },
            j_merry_andy={
                name="满目疮痍",
                },
            j_midas_mask={
                name="希望之面...？",
                text={
                    "打出的所有{C:attention}贤者牌{}",
                    "在计分时",
                    "变为{C:attention}黄金牌{}",
                },
            },
            j_mime={
                name="静默",
                },
            j_misprint={
                name="正体不明",
                },
            j_mr_bones={
                name="偷懒的死神",
                },
            j_mystic_summit={
                name="有顶天变",
                },
            j_obelisk={
                name="林中信号塔",
                },
            j_odd_todd={
                name="丁礼田舞",
                },
            j_onyx_agate={
                name="竹",
                },
            j_oops={
                name="幸运四叶草",
                },
            j_order={
                name="魔法使",
                },
            j_pareidolia={
                name="隙间",
                text={
                    "所有卡牌",
                    "均视为",
                    "{C:attention}贤者牌{}",
                },
            },
            j_photograph={
                name="照片",
                text={
                    "打出的第一张{C:attention}贤者牌{}",
                    "在计分时",
                    "会给予{X:mult,C:white} X#1# {}倍率",
                },
            },
            j_popcorn={
                name="烤八目鳗",
                },
            j_raised_fist={
                name="草根妖怪之力",
                },
            j_ramen={
                name="豚骨拉面",
                },
            j_red_card={
                name="最终鬼畜",
                },
            j_reserved_parking={
                name="神樱树",
                text={
                    "留在手牌中的",
                    "每一张{C:attention}贤者牌{}",
                    "有{C:green}#2#/#3#{}几率",
                    "给予{C:money}$#1#{}",
                },
            },
            j_ride_the_bus={
                name="搭乘巴士",
                text={
                    "连续打出没有",
                    "计分{C:attention}贤者牌{}的牌时",
                    "这张小丑牌获得{C:mult}+#1#{}倍率",
                    "失败将会重置倍率",
                    "{C:inactive}（当前为{C:mult}+#2#{C:inactive}倍率）",
                },
            },
            j_riff_raff={
                name="妖精大战争",
                },
            j_ring_master={
                name="黑市",
                text={
                    "{C:attention}小丑牌{}、{C:tarot}地点牌{}、{C:planet}角色牌{}",
                    "和{C:planet}符卡{}可以同时",
                    "出现复数张",
                },
            },
            j_rocket={
                name="火箭",
                },
            j_rough_gem={
                name="日本槭",
                },
            j_runner={
                name="小恶魔",
                },
            j_satellite={
                name="宴会",
                text={
                    "本赛局每使用过一种",
                    "{C:planet}角色牌{}，每回合结束时",
                    "可得到{C:money}$#1#{}",
                    "{C:inactive}（当前{C:money}$#2#{C:inactive}）",
                },
            },
            j_scary_face={
                name="闲者会议",
                text={
                    "打出的{C:attention}贤者牌{}",
                    "在计分时",
                    "给予{C:chips}+#1#{}筹码",
                },
            },
            j_scholar={
                name="都市魔法使",
                },
            j_seance={
                name="巫女占卜",
                text={
                    "如果{C:attention}牌型{}为",
                    "{C:attention}#1#{}，随机生成",
                    "一张{C:spectral}符卡{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            j_seeing_double={
                name="满月",
                },
            j_selzer={
                name="绿茶",
                },
            j_shoot_the_moon={
                name="碎月",
                },
            j_shortcut={
                name="旧地狱街道",
                },
            j_sixth_sense={
                name="狂气之瞳",
                text={
                    "如果回合的{C:attention}第一次出牌{}",
                    "是一张单独的{C:attention}6{}",
                    "则将其销毁并生成一张{C:spectral}符卡{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            j_sly={
                name="对子蓝点",
                },
            j_smeared={
                name="炫目阳光",
                },
            j_smiley={
                name="观鸟",
                text={
                    "打出的{C:attention}贤者牌{}",
                    "在计分时",
                    "给予{C:mult}+#1#{}倍率",
                },
            },
            j_sock_and_buskin={
                name="黑与白",
                text={
                    "重新触发所有",
                    "打出的{C:attention}贤者牌{}",
                },
                unlock={
                    "打出总共",
                    "{C:attention,E:1}#1#{}张贤者牌",
                    "{C:inactive}(#2#)",
                },
            },
            j_space={
                name="万宝槌",
                },
            j_splash={
                name="擦弹",
                },
            j_square={
                name="游戏币",
                },
            j_steel_joker={
                name="工厂门卡",
                },
            j_stencil={
                name="幕间",
                text={
                    "每个空的{C:attention}小丑牌{}槽位",
                    "获得{X:red,C:white} X1{}倍率",
                    "{s:0.8}幕间算作空位",
                    "（当前为{X:red,C:white} X#1# {C:inactive}）",
                },
            },
            j_stone={
                name="恋之石刻",
                },
            j_stuntman={
                name="过劳",
                },
            j_supernova={
                name="谁是自机？",
                },
            j_superposition={
                name="核动力熔炉",
                text={
                    "如果打出的牌中包含",
                    "一张{C:attention}A{}和一个{C:attention}顺子{}",
                    "生成一张{C:tarot}地点牌{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            j_swashbuckler={
                name="海盗",
                },
            j_throwback={
                name="幻想风靡",
                },
            j_ticket={
                name="索道门票",
                },
            j_to_the_moon={
                name="飘上月球",
                },
            j_todo_list={
                name="秘封活动记录",
                },
            j_trading={
                name="交易卡",
                },
            j_tribe={
                name="巫女",
                },
            j_trio={
                name="现人神",
                },
            j_troubadour={
                name="能乐演出",
                },
            j_trousers={
                name="奇怪的T恤",
                },
            j_turtle_bean={
                name="油豆腐",
                },
            j_vagabond={
                name="流浪汉",
                text={
                    "如果在出牌时",
                    "资金少于等于{C:money}$#1#{}",
                    "则获得一张{C:purple}地点牌{}",
                },
            },
            j_vampire={
                name="吸血鬼",
                },
            j_walkie_talkie={
                name="无网络连接",
                },
            j_wee={
                name="抱B死",
                },
            j_wily={
                name="三条蓝点",
                },
            j_wrathful_joker={
                name="冬日",
                },
            j_zany={
                name="三条P点",
                },

        },
            alt_tex_th_tarots = {
		name = "塔罗牌",
           c_chariot={
                name="雾之湖",
                text={
                    "增强{C:attention}#1#{}张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_death={
                name="白玉楼",
                text={
                    "选定{C:attention}#1#{}张卡牌，",
                    "将{C:attention}靠左{}的那张牌",
                    "变成{C:attention}靠右{}的那张牌",
                    "{C:inactive}（你可以拖动来改变位置）",
                },
            },
            c_devil={
                name="地狱",
                text={
                    "增强{C:attention}#1#{}张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_emperor={
                name="妖怪之山",
                text={
                    "生成最多{C:attention}#1#张",
                    "随机{C:tarot}地点牌{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            c_empress={
                name="博丽神社",
                text={
                    "增强{C:attention}#1#张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_fool={
                name="人间之里",
                text={
                    "生成本赛局中",
                    "上一次使用的",
                    "{C:tarot}地点牌{}或{C:planet}角色牌{}",
                    "不包括{s:0.8,C:tarot}人间之里{s:0.8}",
                },
            },
            c_hanged_man={
                name="辉针城",
                text={
                    "摧毁最多{C:attention}#1#{}张",
                    "选定卡牌",
                },
            },
            c_heirophant={
                name="守矢神社",
                text={
                    "增强{C:attention}#1#张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_hermit={
                name="命莲寺",
                text={
                    "资金加倍",
                    "{C:inactive}（最高{C:money}$#1#{C:inactive}）",
                },
            },
            c_high_priestess={
                name="高空",
                text={
                    "生成最多{C:attention}#1#张",
                    "张随机{C:planet}角色牌{}",
                    "{C:inactive}（必须有空位）",
                },
            },
            c_judgement={
                name="静海",
                text={
                    "生成一张随机的",
                    "{C:attention}{}小丑牌",
                    "{C:inactive}（必须有空位）",
                },
            },
            c_justice={
                name="彼岸",
                text={
                    "增强{C:attention}#1#{}张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_lovers={
                name="后户之国",
                text={
                    "增强{C:attention}#1#{}张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_magician={
                name="魔法之森",
                text={
                    "增强{C:attention}#1#{}张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_moon={
                name="永远亭",
                text={
                    "将最多{C:attention}#1#{}张",
                    "选定卡牌",
                    "转换为{V:1}#2#{}",
                },
            },
            c_star={
                name="玄武涧",
                text={
                    "将最多{C:attention}#1#{}张",
                    "选定卡牌",
                    "转换为{V:1}#2#{}",
                },
            },
            c_strength={
                name="畜生界",
                text={
                    "将最多{C:attention}#1#{}张",
                    "选定卡牌",
                    "点数提高{C:attention}1",
                },
            },
            c_sun={
                name="太阳花田",
                text={
                    "将最多{C:attention}#1#{}张",
                    "选定卡牌",
                    "转换为{V:1}#2#{}",
                },
            },
            c_temperance={
                name="神灵庙",
                text={
                    "获得拥有的小丑牌",
                    "售出价格总和的",
                    "资金{C:inactive}（最高{C:money}$#1#{C:inactive}）",
                    "{C:inactive}（当前{C:money}$#2#{C:inactive}）",
                },
            },
            c_tower={
                name="旧地狱",
                text={
                    "增强{C:attention}#1#{}张",
                    "选定卡牌成为",
                    "{C:attention}#2#",
                },
            },
            c_wheel_of_fortune={
                name="天界",
                text={
                    "有{C:green}#1#/#2#{}几率",
                    "给一张随机{C:attention}小丑牌",
                    "添加{C:dark_edition}闪箔{}、{C:dark_edition}镭射{}",
                    "或{C:dark_edition}多彩{}版本",
                },
            },
            c_world={
                name="幻想乡",
                text={
                    "将最多{C:attention}#1#{}张",
                    "选定卡牌",
                    "转换为{V:1}#2#{}",
                },
            },
		
        },
            alt_tex_th_planets = {
		name = "星球牌",
           c_ceres={
                name="玛艾露贝莉 · 赫恩",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_earth={
                name="铃仙 · 优昙华院 · 因幡",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_eris={
                name="宇佐见莲子",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_jupiter={
                name="博丽灵梦",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_mars={
                name="十六夜咲夜",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_mercury={
                name="魂魄妖梦",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_neptune={
                name="宇佐见堇子",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_planet_x={
                name="？？？",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_pluto={
                name="琪露诺",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_saturn={
                name="雾雨魔理沙",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_uranus={
                name="射命丸文",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },
            c_venus={
                name="东风谷早苗",
                text={
                    "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
                    "升级{C:attention}#2#",
                    "{C:mult}+#3#{}倍率并且",
                    "{C:chips}+#4#{}筹码",
                },
            },

        },
            alt_tex_th_spectrals = {
		name = "幻灵牌",
            c_ankh={
                name="「救世观音的佛光」",
                text={
                    "随机复制一张",
                    "{C:attention}小丑牌{}，摧毁",
                    "其他小丑牌",
                },
            },
            c_aura={
                name="「全人类的绯想天」",
                text={
                    "选定{C:attention}1{}张手牌，为其添加",
                    "{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}、或{C:dark_edition}多彩卡{}",
                    "效果中的一种",
                },
            },
            c_black_hole={
                name="「人类与妖怪的境界」",
                text={
                    "所有{C:legendary,E:1}牌型",
                    "提升{C:attention}1{}级",
                },
            },
            c_cryptid={
                name="「信仰之山」",
                text={
                    "选定手牌中的{C:attention}1{}张牌",
                    "生成{C:attention}#1#{}张其复制牌",
                },
            },
            c_deja_vu={
                name="「红魔」",
                text={
                    "给你手牌中的",
                    "{C:attention}1{}张所选卡牌",
                    "加上{C:red}红色蜡封{}",
                },
            },
            c_ectoplasm={
                name="「地底蔷薇」",
                text={
                    "添加{C:dark_edition}负片{}效果到",
                    "一张随机的{C:attention}小丑牌",
                    "手牌上限{C:red}-#1#{}",
                },
            },
            c_familiar={
                name="「无秩序弹幕地狱」",
                text={
                    "随机摧毁{C:attention}1{}张手牌",
                    "并添加{C:attention}#1#{}张",
                    "随机{C:attention}增强的贤者牌{}",
                    "到手牌中",
                },
            },
            c_grim={
                name="「圣尼公之大空卷轴」",
                text={
                    "随机摧毁{C:attention}1{}张手牌",
                    "并添加{C:attention}#1#{}张",
                    "随机{C:attention}增强的A{}",
                    "到手牌中",
                },
            },
            c_hex={
                name="「纯粹的狂气」",
                text={
                    "随机为一张{C:attention}小丑牌{}添加",
                    "{C:attention}多彩{}，摧毁",
                    "其他小丑牌",
                },
            },
            c_immolate={
                name="「地底太阳」",
                text={
                    "随机摧毁",
                    "{C:attention}#1#{}张手牌",
                    "获得{C:money}$#2#",
                },
            },
            c_incantation={
                name="「七个一寸法师」",
                text={
                    "随机摧毁{C:attention}1{}张手牌",
                    "并添加{C:attention}#1#{}张",
                    "随机{C:attention}增强的数字牌{}",
                    "到手牌中",
                },
            },
            c_medium={
                name="「亡羊的王国」",
                text={
                    "给你手牌中的",
                    "{C:attention}1{}张所选卡牌",
                    "加上{C:purple}紫色蜡封{}",
                },
            },
            c_ouija={
                name="「星尘幻想」",
                text={
                    "将手中所有",
                    "手持牌转换为同一个",
                    "随机{C:attention}点数",
                    "手牌上限{C:red}-1{}",
                },
            },
            c_sigil={
                name="「梦想封印」",
                text={
                    "将手中所有",
                    "卡牌转换为同一种",
                    "随机{C:attention}花色",
                },
            },
            c_soul={
                name="灵魂",
                text={
                    "生成一张",
                    "{C:legendary,E:1}传奇{}小丑牌",
                    "{C:inactive}（必须有空位）",
                },
            },
            c_talisman={
                name="「虹人环」",
                text={
                    "将{C:attention}金色蜡封{}添加到",
                    "{C:attention}1{}张选定的",
                    "手牌中",
                },
            },
            c_trance={
                name="「鬼形造形术」",
                text={
                    "给你手牌中的",
                    "{C:attention}1{}张所选卡牌",
                    "加上{C:blue}蓝色蜡封{}",
                },
            },
            c_wraith={
                name="「最终审判」",
                text={
                    "生成一张随机的",
                    "{C:red}稀有{C:attention}小丑牌{}",
                    "将资金变为{C:money}$0",
                },
            },

        },
            alt_tex_th_boosters = {
		name = "增强包",
            p_arcana_jumbo={
                name="巨型地点包",
                text={
                    "从最多{C:attention}#2#张{C:tarot}地点牌{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_arcana_mega={
                name="超级地点包",
                text={
                    "从最多{C:attention}#2#张{C:tarot}地点牌{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_arcana_normal={
                name="地点包",
                text={
                    "从最多{C:attention}#2#张{C:tarot}地点牌{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_buffoon_jumbo={
                name="巨型小丑包",
                text={
                    "从最多{C:attention}#2#张{C:joker}小丑牌{}中",
                    "选择{C:attention}#1#{}张",
                },
            },
            p_buffoon_mega={
                name="超级小丑包",
                text={
                    "从最多{C:attention}#2#张{C:joker}小丑牌{}中",
                    "选择{C:attention}#1#{}张",
                },
            },
            p_buffoon_normal={
                name="小丑包",
                text={
                    "从最多{C:attention}#2#张{C:joker}小丑牌{}中",
                    "选择{C:attention}#1#{}张",
                },
            },
            p_celestial_jumbo={
                name="巨型角色包",
                text={
                    "从最多{C:attention}#2#张{C:planet}角色牌{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_celestial_mega={
                name="超级角色包",
                text={
                    "从最多{C:attention}#2#张{C:planet}角色牌{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_celestial_normal={
                name="角色包",
                text={
                    "从最多{C:attention}#2#张{C:planet}角色牌{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_spectral_jumbo={
                name="巨型符卡包",
                text={
                    "从最多{C:attention}#2#张{C:spectral}符卡{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_spectral_mega={
                name="超级符卡包",
                text={
                    "从最多{C:attention}#2#张{C:spectral}符卡{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_spectral_normal={
                name="符卡包",
                text={
                    "从最多{C:attention}#2#张{C:spectral}符卡{}中",
                    "选择{C:attention}#1#{}张",
                    "即选即用",
                },
            },
            p_standard_jumbo={
                name="巨型标准包",
                text={
                    "从最多{C:attention}#2#张{C:attention}游戏牌{}中",
                    "选择{C:attention}#1#{}张",
                    "添加到你的牌组",
                },
            },
            p_standard_mega={
                name="超级标准包",
                text={
                    "从最多{C:attention}#2#张{C:attention}游戏牌{}中",
                    "选择{C:attention}#1#{}张",
                    "添加到你的牌组",
                },
            },
            p_standard_normal={
                name="标准包",
                text={
                    "从最多{C:attention}#2#张{C:attention}游戏牌{}中",
                    "选择{C:attention}#1#{}张",
                    "添加到你的牌组",
                },
            },
        },
            alt_tex_th_deck = {
		name = "牌组及强化",
            b_abandoned={
                name="废弃牌组",
                text={
                    "开局时",
                    "玩家牌组中",
                    "没有{C:attention}贤者牌",
                },
            },
            b_ghost={
                name="幽灵牌组",
                text={
                    "商店中可能",
                    "出现{C:spectral}符卡{}",
                    "初始带有{C:spectral,T:c_hex}「纯粹的狂气」{}牌",
                },
            },
        },
            alt_tex_th_enhanced = {
		name = "强化",
            m_glass={
                name="冰冻牌",
                text={
                    "{X:mult,C:white}X#1#{}倍率",
                    "有{C:green}#2#/#3#{}几率",
                    "摧毁此牌",
                },
		},

	},
            alt_tex_th_blinds = {
		name = "盲注",
            bl_mark={
                name="标记",
                text={
                    "所有贤者牌都是",
                    "以背面朝上的方式抽取",
                },
            },
            bl_plant={
                name="植物",
                text={
                    "所有贤者牌",
                    "都被削弱",
                },
            },

	},
            alt_tex_th_vouchers = {
		name = "优惠券",
            v_observatory={
                name="天文台",
                text={
                    "在您{C:attention}消耗牌栏位{}中",
                    "的{C:planet}角色牌{}",
                    "会使这一特定{C:attention}牌型",
                    "给予{X:red,C:white}X#1#{}倍率",
                },
                unlock={
                    "从任何{C:planet}角色包中",
                    "总共使用{C:attention}#1#张",
                    "{C:planet}角色牌{}",
                    "{C:inactive}(#2#)",
                },
            },
            v_omen_globe={
                name="预兆球",
                text={
                    "{C:spectral}符卡{}可能",
                    "会在任何",
                    "{C:attention}地点包中出现",
                },
                unlock={
                    "从任何{C:tarot}地点包中",
                    "总共使用{C:attention}#1#张",
                    "{C:tarot}地点牌{}",
                    "{C:inactive}(#2#)",
                },
            },
            v_planet_merchant={
                name="角色牌商人",
                text={
                    "商店内",
                    "{C:planet}角色牌{}",
                    "出现频率{C:attention}X#1#{}",
                },
            },
            v_planet_tycoon={
                name="角色大亨",
                text={
                    "商店内",
                    "{C:tarot}角色牌{}",
                    "出现频率{C:attention}X#1#{}",
                },
                unlock={
                    "在商店",
                    "购买总计",
                    "{C:attention}#1#{}张{C:planet}角色牌{}",
                    "{C:inactive}(#2#)",
                },
            },
            v_tarot_merchant={
                name="地点牌商人",
                text={
                    "商店内",
                    "{C:tarot}地点牌{}",
                    "出现频率{C:attention}X#1#{}",
                },
            },
            v_tarot_tycoon={
                name="地点大亨",
                text={
                    "商店内",
                    "{C:tarot}地点牌{}",
                    "出现频率{C:attention}X#1#{}",
                },
                unlock={
                    "在商店",
                    "购买总计",
                    "{C:attention}#1#张{C:tarot}地点牌{}",
                    "{C:inactive}(#2#)",
                },
            },
            v_telescope={
                name="望远镜",
                text={
                    "{C:attention}角色包中的",
                    "{C:planet}角色牌{}{}始终有",
                    "你最常用的",
                    "的{C:attention}牌型",
                },
            },
	},

	},
        texture_packs = {
            texpack_th_touhou_cards = {
                name = "东方小丑牌",
        	text = {
            "将小丑牌，消耗牌和部分强化包",
            "以东方project为主题重新绘制",
                },
            },
        },
    },
}
