-- zh-CN.lua (chinese - simplified)
return {
    descriptions = {
        alt_texture = {
            alt_tex_th_jokers = {
            j_8_ball={
                name="地下偶像",
                },
            j_abstract={
                name="阴阳玉",
                },
            j_acrobat={
                name="门扉",
                },
            j_ancient={
                name="鸟居",
                },
            j_arrowhead={
                name="樱花",
                },
            j_astronomer={
                name="求闻史记",
                },
            j_banner={
                name="驱魔棒",
                },
            j_baron={
                name="八云家",
                },
            j_baseball={
                name="当头棒喝",
                },
            j_blackboard={
                name="黑洞洞",
                },
            j_bloodstone={
                name="玫瑰",
                },
            j_blue_joker={
                name="蓝点",
                },
            j_blueprint={
                name="反狱王",
                },
            j_bootstraps={
                name="赛钱箱",
                },
            j_brainstorm={
                name="外来韦编 ALERT",
                },
            j_bull={
                name="弹幕变大术",
                },
            j_burglar={
                name="小偷！",
                },
            j_burnt={
                name="纵火",
                },
            j_business={
                name="名片",
                },
            j_campfire={
                name="暴食",
                },
            j_card_sharp={
                name="出千",
                },
            j_cartomancer={
                name="文文。新闻",
                },
            j_castle={
                name="大图书馆",
                },
            j_cavendish={
                name="极限火花",
                },
            j_ceremonial={
                name="杀意",
                },
            j_certificate={
                name="替身地藏",
                },
            j_chaos={
                name="上海人形",
                },
            j_clever={
                name="两对蓝点",
                },
            j_cloud_9={
                name="冰雪聪明",
                },
            j_constellation={
                name="弹幕烟花大会",
                },
            j_crafty={
                name="同花蓝点",
                },
            j_crazy={
                name="顺子P点",
                },
            j_credit_card={
                name="香霖堂20円代金券",
                },
            j_delayed_grat={
                name="怀表",
                },
            j_devious={
                name="顺子蓝点",
                },
            j_diet_cola={
                name="啤酒",
                },
            j_dna={
                name="一只萃香，两只萃香...",
                },
            j_drivers_license={
                name="驾驶执照",
                },
            j_droll={
                name="同花P点",
                },
            j_drunkard={
                name="伊吹瓢",
                },
            j_duo={
                name="剑士",
                },
            j_dusk={
                name="梦境世界",
                },
            j_egg={
                name="毘沙门天的宝塔",
                },
            j_erosion={
                name="欲望吞噬",
                },
            j_even_steven={
                name="尔子田里乃",
                },
            j_faceless={
                name="下克上",
                },
            j_family={
                name="破坏狂",
                },
            j_fibonacci={
                name="垒石",
                },
            j_flash={
                name="趁虚而入",
                },
            j_flower_pot={
                name="四季",
                },
            j_fortune_teller={
                name="博丽大结界",
                },
            j_four_fingers={
                name="骚灵乐团",
                },
            j_gift={
                name="探宝棒",
                },
            j_glass={
                name="完美冻结",
                },
            j_gluttenous_joker={
                name="夏日",
                },
            j_golden={
                name="资金点",
                },
            j_greedy_joker={
                name="秋日",
                },
            j_green_joker={
                name="大妖精",
                },
            j_gros_michel={
                name="八卦炉",
                },
            j_hack={
                name="M-1漫才",
                },
            j_half={
                name="被撕下一半的通缉令",
                },
            j_hallucination={
                name="花果子念报",
                },
            j_hanging_chad={
                name="未断选票",
                },
            j_hiker={
                name="安眠入梦",
                },
            j_hit_the_road={
                name="这里是...纯狐！",
                },
            j_hologram={
                name="月之都明信片",
                },
            j_ice_cream={
                name="刨冰",
                },
            j_idol={
                name="偶像",
                },
            j_invisible={
                name="幽灵聚会",
                },
            j_joker={
                name="P点",
                },
            j_jolly={
                name="对子P点",
                },
            j_juggler={
                name="星熊杯",
                },
            j_loyalty_card={
                name="借书卡",
                },
            j_luchador={
                name="遗照",
                },
            j_lucky_cat={
                name="招财猫",
                },
            j_lusty_joker={
                name="春日",
                },
            j_mad={
                name="两对P点",
                },
            j_madness={
                name="疯狂",
                },
            j_mail={
                name="检查站",
                },
            j_marble={
                name="恋之fumo",
                },
            j_matador={
                name="final stage",
                },
            j_merry_andy={
                name="满目疮痍",
                },
            j_midas_mask={
                name="希望之面...？",
                },
            j_mime={
                name="静默",
                },
            j_misprint={
                name="正体不明",
                },
            j_mr_bones={
                name="偷懒的死神",
                },
            j_mystic_summit={
                name="有顶天变",
                },
            j_obelisk={
                name="林中信号塔",
                },
            j_odd_todd={
                name="丁礼田舞",
                },
            j_onyx_agate={
                name="竹",
                },
            j_oops={
                name="幸运四叶草",
                },
            j_order={
                name="魔法使",
                },
            j_pareidolia={
                name="隙间",
                },
            j_photograph={
                name="照片",
                },
            j_popcorn={
                name="烤八目鳗",
                },
            j_raised_fist={
                name="草根妖怪之力",
                },
            j_ramen={
                name="豚骨拉面",
                },
            j_red_card={
                name="最终鬼畜",
                },
            j_reserved_parking={
                name="神樱树",
                },
            j_ride_the_bus={
                name="搭乘巴士",
                },
            j_riff_raff={
                name="妖精大战争",
                },
            j_ring_master={
                name="黑市",
                },
            j_rocket={
                name="火箭",
                },
            j_rough_gem={
                name="日本槭",
                },
            j_runner={
                name="小恶魔",
                },
            j_satellite={
                name="宴会",
                },
            j_scary_face={
                name="闲者会议",
                },
            j_scholar={
                name="都市魔法使",
                },
            j_seance={
                name="巫女占卜",
                },
            j_seeing_double={
                name="满月",
                },
            j_selzer={
                name="绿茶",
                },
            j_shoot_the_moon={
                name="碎月",
                },
            j_shortcut={
                name="旧地狱街道",
                },
            j_sixth_sense={
                name="狂气之瞳",
                },
            j_sly={
                name="对子蓝点",
                },
            j_smeared={
                name="炫目阳光",
                },
            j_smiley={
                name="观鸟",
                },
            j_sock_and_buskin={
                name="黑与白",
                },
            j_space={
                name="万宝槌",
                },
            j_splash={
                name="擦弹",
                },
            j_square={
                name="游戏币",
                },
            j_steel_joker={
                name="工厂门卡",
                },
            j_stencil={
                name="幕间",
                },
            j_stone={
                name="恋之石刻",
                },
            j_stuntman={
                name="过劳",
                },
            j_supernova={
                name="谁是自机？",
                },
            j_superposition={
                name="核动力熔炉",
                },
            j_swashbuckler={
                name="海盗",
                },
            j_throwback={
                name="幻想风靡",
                },
            j_ticket={
                name="索道门票",
                },
            j_to_the_moon={
                name="飘上月球",
                },
            j_todo_list={
                name="秘封活动记录",
                },
            j_trading={
                name="交易卡",
                },
            j_tribe={
                name="巫女",
                },
            j_trio={
                name="现人神",
                },
            j_troubadour={
                name="能乐演出",
                },
            j_trousers={
                name="奇怪的T恤",
                },
            j_turtle_bean={
                name="油豆腐",
                },
            j_vagabond={
                name="流浪汉",
                },
            j_vampire={
                name="吸血鬼",
                },
            j_walkie_talkie={
                name="无网络连接",
                },
            j_wee={
                name="抱B死",
                },
            j_wily={
                name="三条蓝点",
                },
            j_wrathful_joker={
                name="冬日",
                },
            j_zany={
                name="三条P点",
                },

        },
	},
        texture_packs = {
            texpack_th_touhou_cards = {
                name = "东方小丑牌",
        	text = {
            "所有小丑牌（139张）",
            "都以东方project为主题被重新绘制了！",
                },
            },
        },
    },
}
